version: 2.1
executors:
  app-executor:
    docker:
      - image: cimg/node:16.17.0
      - image: 'cibuilds/base:latest'
    working_directory: ~/repo

aliases:
  - &show-current-branch-name
    run:
      name: Show current branch
      command: echo ${CIRCLE_BRANCH}
  - &restore-cache
    restore_cache:
      keys:
        - app-{{ checksum "package.json" }}
        - app-
  - &install-dependencies
    run:
      name: Install dependencies
      command: npm install
  - &save-cache
    save_cache:
      paths:
        - node_modules
      key: app-{{ checksum "package.json" }}

jobs:
  install-dependencies:
    executor: app-executor
    steps:
      - checkout
      - *show-current-branch-name
      - *restore-cache
      - *install-dependencies
      - *save-cache

  linting:
    executor: app-executor
    steps:
      - checkout
      - *show-current-branch-name
      - *restore-cache
      - run:
          name: Run linting
          command: npm run lint:check

  code-formatter-check:
    executor: app-executor
    steps:
      - checkout
      - *show-current-branch-name
      - *restore-cache
      - run:
          name: Run prettier check
          command: npm run prettier:check

  unit-test:
    executor: app-executor
    steps:
      - checkout
      - *show-current-branch-name
      - *restore-cache
      - run:
          name: Run unit test
          command: npm run test

workflows:
  build_and_deploy:
    jobs:
      - install-dependencies
      - linting:
          requires:
            - install-dependencies
          filters:
            branches:
              only:
                - develop
                - staging
                - main
      - code-formatter-check:
          requires:
            - linting
          filters:
            branches:
              only:
                - develop
                - staging
                - main
      - unit-test:
          requires:
            - code-formatter-check
          filters:
            branches:
              only:
                - develop
                - staging
                - main
